# Generated by Django 4.2.7 on 2023-12-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ccode',
        ),
    ]
